language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PROJ=${PWD##*/}

install:
  - pip install -r test-requirements.txt
  - cp settings.example.py settings.py

script:
  - flake8 $PROJ
  - pytest --cov=$PROJ -v tests
